use crate::model::{Domain, Inventory};
use std::collections::BTreeMap;
use std::fmt::Write;

/// Render the inventory as a human-readable AGENT_MAP.md ledger (FR-2).
pub fn to_agent_map(inv: &Inventory) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# AGENT_MAP.md");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "> Auto-generated by IO Inventory on {} for `{}` ({}).",
        inv.scan.finished_at, inv.scan.host, inv.scan.os
    );
    let _ = writeln!(out, "> {} items across the environment.", inv.scan.item_count);
    let _ = writeln!(out);

    write_tagged_views(&mut out, inv);

    let order = [
        Domain::Project,
        Domain::PackageManager,
        Domain::Runtime,
        Domain::AiAgent,
        Domain::Container,
    ];

    for domain in order {
        let items: Vec<_> = inv
            .items
            .iter()
            .filter(|i| i.domain == domain)
            .collect();
        if items.is_empty() {
            continue;
        }
        let _ = writeln!(out, "## {}", domain.label());
        let _ = writeln!(out);

        if domain == Domain::Project {
            write_projects(&mut out, &items);
            continue;
        }

        // Group by collector.
        let mut by_collector: BTreeMap<&str, Vec<_>> = BTreeMap::new();
        for it in &items {
            by_collector.entry(it.collector.as_str()).or_default().push(*it);
        }
        for (collector, list) in by_collector {
            // Most of Homebrew and pip is transitive. Listing all of it buries
            // the handful of things that were actually chosen, so dependencies
            // are counted rather than enumerated — anything annotated still
            // gets its line, since a note means the user cared about it.
            let (chosen, deps): (Vec<&crate::model::Item>, Vec<&crate::model::Item>) = list
                .iter()
                .copied()
                .partition(|it| !crate::graph::is_dependency(it) || has_annotation(it));
            let _ = writeln!(out, "### {} ({})", collector, list.len());
            let _ = writeln!(out);
            for it in &chosen {
                let ver = it.version.as_deref().map(|v| format!(" `{v}`")).unwrap_or_default();
                let note = it
                    .why
                    .as_deref()
                    .filter(|s| !s.is_empty())
                    .map(|w| format!(" — {w}"))
                    .unwrap_or_default();
                let _ = writeln!(out, "- **{}**{}{}{}", it.name, ver, note, tag_suffix(it));
            }
            if !deps.is_empty() {
                let _ = writeln!(
                    out,
                    "- _…plus {} pulled in as dependencies._",
                    deps.len()
                );
            }
            let _ = writeln!(out);
        }
    }
    out
}

/// Whether the user has said anything about this item — a note or a tag. Enough
/// to keep it in the ledger even if it's only here as a dependency.
fn has_annotation(it: &crate::model::Item) -> bool {
    !it.tags.is_empty()
        || it.why.as_deref().is_some_and(|s| !s.is_empty())
        || it.note.as_deref().is_some_and(|s| !s.is_empty())
}

/// Format an item's tags as a trailing ` _[a, b]_` marker.
fn tag_suffix(it: &crate::model::Item) -> String {
    if it.tags.is_empty() {
        String::new()
    } else {
        format!("  _[{}]_", it.tags.join(", "))
    }
}

/// A "Tagged Views" section: each tag lists the items carrying it, so a saved
/// view (e.g. "favorites") is legible straight from the ledger.
fn write_tagged_views(out: &mut String, inv: &Inventory) {
    let mut by_tag: BTreeMap<&str, Vec<&crate::model::Item>> = BTreeMap::new();
    for it in &inv.items {
        for tag in &it.tags {
            by_tag.entry(tag.as_str()).or_default().push(it);
        }
    }
    if by_tag.is_empty() {
        return;
    }
    let _ = writeln!(out, "## Tagged Views");
    let _ = writeln!(out);
    for (tag, items) in &by_tag {
        let _ = writeln!(out, "### #{} ({})", tag, items.len());
        let _ = writeln!(out);
        for it in items {
            let ver = it.version.as_deref().map(|v| format!(" `{v}`")).unwrap_or_default();
            let _ = writeln!(out, "- **{}**{} · _{}_", it.name, ver, it.collector);
        }
        let _ = writeln!(out);
    }
    let _ = writeln!(out, "---");
    let _ = writeln!(out);
}

fn write_projects(out: &mut String, items: &[&crate::model::Item]) {
    for it in items {
        let stacks = it
            .metadata
            .get("stacks")
            .and_then(|s| s.as_array())
            .map(|a| {
                a.iter()
                    .filter_map(|x| x.as_str())
                    .collect::<Vec<_>>()
                    .join(", ")
            })
            .unwrap_or_default();
        let launch = it
            .metadata
            .get("launch_cmd")
            .and_then(|v| v.as_str())
            .filter(|s| !s.is_empty());
        let _ = writeln!(out, "### {}", it.name);
        if !stacks.is_empty() {
            let _ = writeln!(out, "- Stack: {stacks}");
        }
        if let Some(cmd) = launch {
            let _ = writeln!(out, "- Launch: `{cmd}`");
        }
        if let Some(p) = &it.source_path {
            let _ = writeln!(out, "- Path: `{p}`");
        }
        if let Some(why) = it.why.as_deref().filter(|s| !s.is_empty()) {
            let _ = writeln!(out, "- Note: {why}");
        }
        if !it.tags.is_empty() {
            let _ = writeln!(out, "- Tags: {}", it.tags.join(", "));
        }
        let _ = writeln!(out);
    }
}
