use crate::model::{Domain, Inventory};
use std::collections::BTreeMap;
use std::fmt::Write;

/// Render the inventory as a human-readable AGENT_MAP.md ledger (FR-2).
pub fn to_agent_map(inv: &Inventory) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "# AGENT_MAP.md");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "> Auto-generated by IO Inventory on {} for `{}` ({}).",
        inv.scan.finished_at, inv.scan.host, inv.scan.os
    );
    let _ = writeln!(out, "> {} items across the environment.", inv.scan.item_count);
    let _ = writeln!(out);

    let order = [
        Domain::Project,
        Domain::PackageManager,
        Domain::Runtime,
        Domain::AiAgent,
        Domain::Container,
    ];

    for domain in order {
        let items: Vec<_> = inv
            .items
            .iter()
            .filter(|i| i.domain == domain)
            .collect();
        if items.is_empty() {
            continue;
        }
        let _ = writeln!(out, "## {}", domain.label());
        let _ = writeln!(out);

        if domain == Domain::Project {
            write_projects(&mut out, &items);
            continue;
        }

        // Group by collector.
        let mut by_collector: BTreeMap<&str, Vec<_>> = BTreeMap::new();
        for it in &items {
            by_collector.entry(it.collector.as_str()).or_default().push(*it);
        }
        for (collector, list) in by_collector {
            let _ = writeln!(out, "### {} ({})", collector, list.len());
            let _ = writeln!(out);
            for it in list {
                let ver = it.version.as_deref().map(|v| format!(" `{v}`")).unwrap_or_default();
                let note = it
                    .why
                    .as_deref()
                    .filter(|s| !s.is_empty())
                    .map(|w| format!(" — {w}"))
                    .unwrap_or_default();
                let _ = writeln!(out, "- **{}**{}{}", it.name, ver, note);
            }
            let _ = writeln!(out);
        }
    }
    out
}

fn write_projects(out: &mut String, items: &[&crate::model::Item]) {
    for it in items {
        let stacks = it
            .metadata
            .get("stacks")
            .and_then(|s| s.as_array())
            .map(|a| {
                a.iter()
                    .filter_map(|x| x.as_str())
                    .collect::<Vec<_>>()
                    .join(", ")
            })
            .unwrap_or_default();
        let launch = it
            .metadata
            .get("launch_cmd")
            .and_then(|v| v.as_str())
            .filter(|s| !s.is_empty());
        let _ = writeln!(out, "### {}", it.name);
        if !stacks.is_empty() {
            let _ = writeln!(out, "- Stack: {stacks}");
        }
        if let Some(cmd) = launch {
            let _ = writeln!(out, "- Launch: `{cmd}`");
        }
        if let Some(p) = &it.source_path {
            let _ = writeln!(out, "- Path: `{p}`");
        }
        if let Some(why) = it.why.as_deref().filter(|s| !s.is_empty()) {
            let _ = writeln!(out, "- Note: {why}");
        }
        let _ = writeln!(out);
    }
}
